[package]
name = "aoc01"
version = "0.1.0"
authors = ["Nick Mavis <itsnick@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.6" 
